version: '3.3'

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=retrowave
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "3306:3306"